name: Go Format Action

on:
  push:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Format code
        uses: Jerome1337/gofmt-action@v1.0.4
        with:
          gofmt-path: "./src"
          gofmt-flags: "-l -d"
